// <auto-generated />
using System;
using InterfazRiesgosSimefin_API.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterfazRiesgosSimefin_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231128183141_CrearDataBase")]
    partial class CrearDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InterfazRiesgosSimefin_API.Models.Portafolio", b =>
                {
                    b.Property<int>("IdPortafolio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPortafolio"), 1L, 1);

                    b.Property<string>("F_Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("No_Envio")
                        .HasColumnType("int");

                    b.Property<string>("NombrePortafolio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubPortafolio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("listaDatos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPortafolio");

                    b.ToTable("Portafolios");

                    b.HasData(
                        new
                        {
                            IdPortafolio = 1,
                            F_Posicion = "20231127",
                            FechaCreacion = new DateTime(2023, 11, 28, 12, 31, 41, 491, DateTimeKind.Local).AddTicks(3215),
                            FechaModificacion = new DateTime(2023, 11, 28, 12, 31, 41, 491, DateTimeKind.Local).AddTicks(3222),
                            No_Envio = 1,
                            NombrePortafolio = "TOTAL",
                            SubPortafolio = "DERIVADOS DE NEGOCIACION",
                            listaDatos = "3208895.824"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
